In [3]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [4]:
dataset = pd.read_csv('titanicjyo_data.csv')
X = dataset.iloc[:, :-1]
y = dataset.iloc[:, 4]

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [6]:
"""from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
sc_y = StandardScaler()
y_train = sc_y.fit_transform(y_train)"""

'from sklearn.preprocessing import StandardScaler\nsc_X = StandardScaler()\nX_train = sc_X.fit_transform(X_train)\nX_test = sc_X.transform(X_test)\nsc_y = StandardScaler()\ny_train = sc_y.fit_transform(y_train)'

In [7]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [8]:
y_pred = regressor.predict(X_test)

In [9]:
y_pred

array([ 1.46586699e+01,  6.86771395e+01,  1.04339692e+02,  3.51936363e+01,
        7.48920232e+01,  1.25870420e+01,  5.09906615e+01,  7.32436943e+01,
        6.47928372e+01,  6.94540000e+01,  1.71013312e+00,  6.74319164e-01,
        1.48221530e+01, -2.69207618e+00,  4.51293393e+01,  3.02735201e+01,
        3.59704968e+01,  2.77665532e+01,  1.80939403e+01,  3.44167759e+01,
        2.22804009e+00,  3.41578224e+01,  4.69420137e+01,  5.94885937e+00,
       -3.61494787e-01,  2.77665532e+01,  7.23024884e+01,  3.90779386e+01,
        8.06844704e+01,  3.10037101e+00, -8.79401763e-01,  3.95456626e+01,
        2.22804009e+00,  7.42106332e+01, -1.65626223e+00,  4.98192044e+00,
        7.78359820e+01,  7.23024884e+01,  2.22804009e+00,  9.57420820e+00,
        1.71013312e+00,  1.96908660e+00,  7.68001681e+01,  8.46376478e+01,
        1.56412189e-01,  6.11234241e+00,  4.77375662e+01,  5.04038795e+01,
       -1.65626223e+00,  6.20781286e+00,  7.17845814e+01,  3.83010782e+01,
        3.80421247e+01,  7.33383023e+01,  2.97556131e+01,  6.98467332e+00,
        4.96004236e+01,  6.98467332e+00,  2.84608456e+01,  7.68001681e+01,
        8.02354385e+01, -5.79951803e+00,  5.22854290e+01,  2.22804009e+00,
        7.74815581e+01,  1.43997165e+01,  7.12666744e+01,  3.54525898e+01,
        1.04060022e+02,  8.41197408e+01,  1.71013312e+00,  9.52556032e+01,
        5.67565133e+01,  8.60278856e+01,  6.66055116e+01,  7.46330697e+01,
        2.74594707e+00,  2.48699358e+00, -1.02541299e-01,  3.85600317e+01,
        1.57492065e+01,  7.49874937e+01,  6.99719070e+01,  5.28722110e+01,
        6.66055116e+01,  1.19222614e+00,  1.31049490e+01,  3.95622092e+01,
        9.04989700e+01,  2.97556131e+01,  8.19792379e+01,  1.32170288e+00,
        1.45117963e+00,  3.79919417e+01,  6.55696977e+01,  4.74786128e+01,
        7.91307495e+01,  1.11968042e+01,  6.74319164e-01,  1.36228560e+01,
        7.24362681e+00,  7.43741163e+01,  3.28630549e+01,  7.23024884e+01,
        8.27560983e+01,  3.70063107e+01,  7.54099302e+01,  7.47285402e+01,
        7.89406710e+01,  3.59203138e+01,  1.96908660e+00,  6.46676635e+00,
        4.14272121e+01,  5.81467512e+01,  1.04906620e+02, -8.79401763e-01,
        3.57115433e+01,  8.89281819e+00,  4.41624004e+01,  4.01137526e+01,
        2.48699358e+00,  4.33166649e+01,  1.27771205e+01,  1.56412189e-01,
        8.26614903e+01,  4.12450370e+01,  6.40338064e+01, -5.02265757e+00,
       -3.72789013e+00,  3.51936363e+01,  7.21390053e+01, -4.24579710e+00,
        9.15347839e+01,  7.25614418e+01,  7.46330697e+01,  1.96908660e+00,
        7.96486565e+01,  2.66660008e+01,  4.27987579e+01,  2.48699358e+00,
        3.60999735e+01, -2.43312269e+00,  6.12541930e+01])

In [10]:
import warnings 
warnings.filterwarnings('ignore')

In [11]:
import sklearn
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error

In [12]:
print(mean_squared_error(y_test,y_pred))

1003.6831426491034

In [13]:
print(mean_absolute_error(y_test,y_pred))

20.657955581770768

In [14]:
 print(r2_score(y_test,y_pred))

0.535838092695144

In [15]:
dataset

     Pclass   Age  SibSp  Parch      Fare
0         3  22.0      1      0    7.2500
1         1  38.0      1      0   71.2833
2         3  26.0      0      0    7.9250
3         1  35.0      1      0   53.1000
4         3  35.0      0      0    8.0500
5         1  54.0      0      0   51.8625
6         3   2.0      3      1   21.0750
7         3  27.0      0      2   11.1333
8         2  14.0      1      0   30.0708
9         3   4.0      1      1   16.7000
10        1  58.0      0      0   26.5500
11        3  20.0      0      0    8.0500
12        3  39.0      1      5   31.2750
13        3  14.0      0      0    7.8542
14        2  55.0      0      0   16.0000
15        3   2.0      4      1   29.1250
16        3  31.0      1      0   18.0000
17        2  35.0      0      0   26.0000
18        2  34.0      0      0   13.0000
19        3  15.0      0      0    8.0292
20        1  28.0      0      0   35.5000
21        3   8.0      3      1   21.0750
22        3  38.0      1      5   31.3875
23        1  19.0      3      2  263.0000
24        1  40.0      0      0   27.7208
25        2  66.0      0      0   10.5000
26        1  28.0      1      0   82.1708
27        1  42.0      1      0   52.0000
28        3  21.0      0      0    8.0500
29        3  18.0      2      0   18.0000
..      ...   ...    ...    ...       ...
684       1  45.0      1      1  164.8667
685       1  51.0      0      0   26.5500
686       3  24.0      0      3   19.2583
687       3  41.0      2      0   14.1083
688       2  21.0      1      0   11.5000
689       1  48.0      0      0   25.9292
690       2  24.0      0      0   13.0000
691       2  42.0      0      0   13.0000
692       2  27.0      1      0   13.8583
693       1  31.0      0      0   50.4958
694       3   4.0      1      1   11.1333
695       3  26.0      0      0    7.8958
696       1  47.0      1      1   52.5542
697       1  33.0      0      0    5.0000
698       3  47.0      0      0    9.0000
699       2  28.0      1      0   24.0000
700       3  15.0      0      0    7.2250
701       3  20.0      0      0    9.8458
702       3  19.0      0      0    7.8958
703       1  56.0      0      1   83.1583
704       2  25.0      0      1   26.0000
705       3  33.0      0      0    7.8958
706       3  22.0      0      0   10.5167
707       2  28.0      0      0   10.5000
708       3  25.0      0      0    7.0500
709       3  39.0      0      5   29.1250
710       2  27.0      0      0   13.0000
711       1  19.0      0      0   30.0000
712       1  26.0      0      0   30.0000
713       3  32.0      0      0    7.7500

[714 rows x 5 columns]

In [16]:
X

     Pclass   Age  SibSp  Parch
0         3  22.0      1      0
1         1  38.0      1      0
2         3  26.0      0      0
3         1  35.0      1      0
4         3  35.0      0      0
5         1  54.0      0      0
6         3   2.0      3      1
7         3  27.0      0      2
8         2  14.0      1      0
9         3   4.0      1      1
10        1  58.0      0      0
11        3  20.0      0      0
12        3  39.0      1      5
13        3  14.0      0      0
14        2  55.0      0      0
15        3   2.0      4      1
16        3  31.0      1      0
17        2  35.0      0      0
18        2  34.0      0      0
19        3  15.0      0      0
20        1  28.0      0      0
21        3   8.0      3      1
22        3  38.0      1      5
23        1  19.0      3      2
24        1  40.0      0      0
25        2  66.0      0      0
26        1  28.0      1      0
27        1  42.0      1      0
28        3  21.0      0      0
29        3  18.0      2      0
..      ...   ...    ...    ...
684       1  45.0      1      1
685       1  51.0      0      0
686       3  24.0      0      3
687       3  41.0      2      0
688       2  21.0      1      0
689       1  48.0      0      0
690       2  24.0      0      0
691       2  42.0      0      0
692       2  27.0      1      0
693       1  31.0      0      0
694       3   4.0      1      1
695       3  26.0      0      0
696       1  47.0      1      1
697       1  33.0      0      0
698       3  47.0      0      0
699       2  28.0      1      0
700       3  15.0      0      0
701       3  20.0      0      0
702       3  19.0      0      0
703       1  56.0      0      1
704       2  25.0      0      1
705       3  33.0      0      0
706       3  22.0      0      0
707       2  28.0      0      0
708       3  25.0      0      0
709       3  39.0      0      5
710       2  27.0      0      0
711       1  19.0      0      0
712       1  26.0      0      0
713       3  32.0      0      0

[714 rows x 4 columns]